### ISSUE TITLE
xin hỏi về tài liệu quyển Designing Data-Intensive Applications

### ISSUE THREAD

**Issue by longpt233** [tuananhhedspibk/BookReview#1]
Hi anh, 

Trước đây em thấy anh có public bản tóm tắt quyển Designing Data-Intensive Applications, nhưng giờ em đang không tìm được, không biết a có thể public lại không ạ. 

Em cảm ơn.

**Comment by tuananhhedspibk** [comment]
Hiện mình đang có chút chỉnh sửa lại nội dung, cuối tuần này nếu xong, mình sẽ public lại. Cảm ơn bạn đã theo dõi.
